
<html>
  <head>
    <title>G10 Job Openings</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <!--<link href="css/bootstrap.min.css" rel="stylesheet"> -->
      <!-- Latest compiled and minified CSS -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

      
      <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    
    <!--Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic|Alegreya+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    
       
    <link href="snippet.css" rel="stylesheet">

  
    <style type="text/css">
    </style>
  </head>
  <body>
    <section class="bootshape">
      <div class="center-block main">
        <div class="head">
          <div class="person">
            <img src="img/logo.svg" style="float:left; padding-left:10px;">
            <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav pull-right">
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Job Opportunitites<b class="caret"></b></a>
                    <ul class="dropdown-menu multi-level">
			   <li><a href="executive-assistant.php">Executive Assistant to Director</a></li>
                        <li><a href="senior-developer.php">Senior Developer</a></li>
                        <li><a href="crm-consultant.php">SAP ASSOCIATE - CRM Consultant</a></li>
                        <li><a href="crm-developer.php">SAP ASSOCIATE - CRM Developer</a></li>
                        <li><a href="eam-consultant.php">SAP ASSOCIATE - EAM Consultant</a></li>
                        <li><a href="fica-consultant.php">SAP ASSOCIATE - FICA Consultant</a></li>
                        <li><a href="billing-consultant.php">SAP ASSOCIATE - Billing Consultant</a></li>
                        <li><a href="sas-administrator.php">SAS Administrator</a></li>
                        <li><a href="android.php">Android Developer</a></li>
						<li><a href="ios.php">iOS Developer</a></li>
						<li><a href="python.php">Python Developer</a></li>
						<li><a href="front-end.php">UI/UX Designer</a></li>
		        <li><a href="grads.php">College Graduates</a></li>
            <li><a href="finance-executive.php">Finance Executive</a></li>
						<li><a href="sales-associate.php">Sales Associate</a></li>

                        
                    </ul>

                </li>
            </ul>
                </div>
          </div>
        </div>

